version: '2'
services:
  mongo:
    image: mongo
  # rabbitmq:
  #   image: rabbitmq
  eureka-server:
    build: eureka-server
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8010:8010"
  config-server:
    build: config-server
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8020:8020"
     # depends_on:
     #   - rabbitmq
  turbine-server:
    build: turbine-server
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8030:8030"
  edge-server:
    build: edge-server
    restart: always
    command: bash -c "wait-for-it -t 0 eureka-server:8010 && java -jar /app/edge-server-latest.jar"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8040:8040"      
  event-service:
    build: event-service
    restart: always
    command: bash -c "wait-for-it -t 0 eureka-server:8010 && java -jar /app/event-service-latest.jar"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "9000:9000"
    depends_on:
      - mongo
      - eureka-server
      # - config-server
  review-service:
    build: review-service
    restart: always
    command: bash -c "wait-for-it -t 0 eureka-server:8010 && java -jar /app/review-service-latest.jar"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "9010:9010"
    depends_on:
      - eureka-server
  # recommendation-service:
  #   build: recommendation-service
  #   restart: always
  #   command: bash -c "wait-for-it eureka-server:8010 && java -jar /app/recommendation-service-latest.jar"
  #   environment:
  #     SPRING_PROFILES_ACTIVE: docker
  #   ports:
  #     - "9020:9020"
  #   depends_on:
  #     - eureka-server
  event-composite-service:
    build: event-composite-service
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
    command: bash -c "wait-for-it -t 0 eureka-server:8010 && java -jar /app/event-composite-service-latest.jar"
    ports:
      - "9030:9030"
    depends_on:
      - eureka-server