eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
server:
  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.

---
spring:
  profiles: docker

server:
  port: 9020

eureka:
  instance:
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8010/eureka/