eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/

server:
  port: 8030
  
info:
  component: Turbine

turbine:
  clusterNameExpression: new String("default")
  appConfig: event-composite

---
spring:
  profiles: docker

server:
  port: 8030

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8010/eureka/